[package]
name = "snips-nlu-ontology-rs"
version = "0.56.0"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]

[dependencies]
failure = "0.1"
ffi-utils = { git = "https://github.com/snipsco/snips-utils-rs", rev = "b1f4af3" }
lazy_static = "1.0"
libc = "0.2"
snips-nlu-ontology = { path = "../../../snips-nlu-ontology" }
snips-nlu-ontology-ffi-macros = { path = "../../../snips-nlu-ontology-ffi-macros" }
snips-nlu-ontology-parsers-ffi-macros = { path = "../../../snips-nlu-ontology-parsers-ffi-macros" }

[lib]
name = "snips_nlu_ontology_rs"
crate-type = ["cdylib"]
