[package]
name = "snips-nlu-ontology-doc"
version = "0.63.2"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]
edition = "2018"

[build-dependencies]
snips-nlu-ontology = { path = ".." }
prettytable-rs = "0.6"
