[package]
name = "snips-nlu-ontology-ffi"
version = "0.53.2"
authors = [
    "Kevin Lefevre <kevin.lefevre@snips.ai>",
    "Thibaut Lorrain <thibaut.lorrain@snips.ai>",
]

[features]
default = ["builtin_entities"]
builtin_entities = ["snips-nlu-ontology/builtin_entities"]

[dependencies]
snips-nlu-ontology = { path = "..", default-features = false }
error-chain = { version = "0.11", default-features = false }
lazy_static = "1.0"
libc = "0.2"
serde = "1.0"
serde_json = "1.0"

[build-dependencies]
cbindgen = "0.4"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
